# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Crossing Paths' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Crossing Paths

  target 'Crossing PathsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Crossing PathsUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'

end
